# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 2, 17, 4, 21, 44, 642612))),
            ],
        ),
    ]
