# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxcomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 4, 23, 13, 501956, tzinfo=utc)),
        ),
    ]
